name: Ngrok RDP Windows

on: 
  [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download Ngrok
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
          Expand-Archive -Path "ngrok.zip" -DestinationPath "$PWD"

      - name: Authenticate Ngrok
        shell: pwsh
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

      - name: Enable Remote Desktop
        shell: pwsh
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 1
          net user runneradmin "Password123"

      - name: Run Ngrok Tunnel (RDP)
        shell: pwsh
        run: |
          Start-Process -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389" -NoNewWindow
          Start-Sleep -Seconds 5
          Invoke-WebRequest -Uri "http://127.0.0.1:4040/api/tunnels" -OutFile "tunnels.json"
          Get-Content tunnels.json
